### ISSUE TITLE
Thanks for this book, question regarding secrets.

### ISSUE THREAD

**Issue by jantuitman** [semaphoreci/book-cicd-docker-kubernetes#5]
Hi semaphore team,

How wonderful that you made this e-book. We have a Docker-compose pipeline set up on semaphoreci which does build images and tags them (and runs the tests of course!). It all works very nicely, but we don’t have Kubernetes and production deployments yet, so the book will be a great resource.
After first read I think your examples don’t illustrate the “secrets pipeline”. I don’t think this is merely an implementation detail as nearly every real world application has settings and secret settings. Which can be different in production then on staging.
I struggled with getting this right in the current setup we have. So I also would like to see this in the book, because I have no clue yet how to deploy environment variables and passwords to Kubernetes environments. 

Would it be possible to include this topic in the book?

**Comment by TomFern** [comment]
@jantuitman thank you for the kind words. I'm happy that you're enjoying the book. 

You can define environment variables for your pods in the deployment manifests. For secrets, you can use `kubectl create secret` to store sensitive data. You can reference the secrets you create in your manifests.

This tutorial shows an example of a [Kubernetes secret](https://kubernetes.io/docs/concepts/configuration/secret/) used to pull an image from a private repository:

https://semaphoreci.com/blog/cicd-microservices-digitalocean-kubernetes

Does this help? Let me know if you're still having trouble.
